
global:
  realm:  &default_realm hopsworks.ai
  basedn: &baseDN dc=hopsworks,dc=ai
  adminName: &admin_name cn=admin,dc=hopsworks,dc=ai
  adminPassword: &admin_password adminpw
  serverName: &server_name hopsworks
  keytabConfigmap: &keytabs_configmap keytabs-configmap
kerberos:
  keytab:
    configmap: *keytabs_configmap
  kdc:
    password: *admin_password
  krb5:
    default_realm: *default_realm
  ldap:
    basedn: *baseDN
    domain: *default_realm
    ou: "Hopsworks Inc."

krb-client:
  default_realm: *default_realm

payara:
  deployPayara: true
  node:
    fullnameOverride: *server_name
  ldap:
    jndilookupname: *baseDN
    property:
      security:
        principal: *admin_name
        credentials: *admin_password
