apiVersion: v1
kind: ConfigMap
metadata:
  name: server-krb5-config
  labels:
    app: {{ template "kerberos.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: krb5
data:
  krb5.conf: |-
    [libdefaults]
        default_realm = {{ .Values.krb5.default_realm | upper }}
    [realms]
        {{ .Values.krb5.default_realm | upper }} = {
            kdc = {{ template "kerberos.fullname" $ }}-kdc.{{ $.Release.Namespace }}.svc.cluster.local:{{ $.Values.kdc.udp.port }}
            master_kdc = {{ template "kerberos.fullname" $ }}-kdc.{{ $.Release.Namespace }}.svc.cluster.local:{{ $.Values.kdc.udp.port }}
            admin_server = {{ template "kerberos.fullname" $ }}-kadmin.{{ $.Release.Namespace }}.svc.cluster.local:749
            default_domain = cluster.local
        }