{{- if .Values.deployPayara -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hazelcast-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - pods
      - nodes
      - services
      - configmaps
    verbs:
      - get
      - list
      - create
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"] # needed to restart hopsworks instances on DAS pod restart

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hazelcast-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hazelcast-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "payara.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

{{- end }}