{{- if .Values.deployPayara -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-configmap
data:
  init_2_change_password.sh: |-
{{ tpl (.Files.Get "resources/init_2_change_password.sh") . | indent 8 }}
  init_3_krb_auth_module.sh: |-
{{ tpl (.Files.Get "resources/init_3_krb_auth_module.sh") . | indent 8 }}
  init_4_copy_asadmin_record.sh: |-
{{ tpl (.Files.Get "resources/init_4_copy_asadmin_record.sh") . | indent 8 }}
  post-boot-commands.asadmin: |-
{{ tpl (.Files.Get "resources/post-boot-commands.asadmin") . | indent 8 }}
#   domain.xml: |-
# {{ tpl (.Files.Get "resources/domain.xml") . | indent 8 }}
{{- end }}
