apiVersion: v1
kind: Secret
metadata:
  name: {{ include "payara.fullname" . }}-server
  labels:
    {{- include "payara.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.server.adminPassword }}
  admin-password: {{ .Values.server.adminPassword | b64enc | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}